# Generated by Django 2.2.10 on 2020-06-21 04:35

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shared_schedule', '0002_auto_20200621_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='eventColor',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
